export default interface MatchSummary {
    championKey: number,
    championIconUrl: string,
    kills: number,
    deaths: number,
    assists: number,
    item0Id: number,
    item1Id: number,
    item2Id: number,
    item3Id: number,
    item4Id: number,
    item5Id: number,
    item0IconUrl: string,
    item1IconUrl: string,
    item2IconUrl: string,
    item3IconUrl: string,
    item4IconUrl: string,
};
